name: Test 6

env:
  ASSIGNMENT_DIR: './Assignments/Assignment_6'  # Directory of Assignment
  TEST_CLASS: Assignment6Tests # Test Class Name

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - 'Assignments/Assignment_6/**/*.java' # should be the same as env.ASSIGNMENT_DIR. for some stupid reason on.push.paths doesnt support variables
      
jobs:
  Compile-and-Test:
    name: Compile and Test
    defaults:
      run:
        working-directory: '${{ env.ASSIGNMENT_DIR }}'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22.0.2'
        distribution: 'temurin'  

    - name: Compile ${{ env.TEST_CLASS}}
      run: javac -cp ".;lib\\junit-platform-console-standalone-1.11.3.jar" '${{ env.TEST_CLASS}}.java'

    - name: Test ${{ env.TEST_CLASS}}
      run: java -jar lib\junit-platform-console-standalone-1.11.3.jar --class-path . --select-class '${{ env.TEST_CLASS }}'
